---
version: '3.3'
services:
  db:
    image: novucs/derby:10.14.2.0-jdk11-slim
    restart: always
    volumes:
      - db-data:/dbs

  app:
    image: novucs/glassfish:5.1.0-jdk8-slim
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:derby://db:1527/esd;create=true
      DEVELOPMENT_MODE: 1
    ports:
      - "8080:8080"
    volumes:
      - autodeploy:/app/glassfish/domains/domain1/autodeploy

  jenkins:
    build: jenkins
    restart: always
    ports:
      - "8081:8080"
    secrets:
      - jenkins_user
      - jenkins_pass
      - github_user
      - github_pass
    volumes:
      - autodeploy:/volume_data

volumes:
  db-data:
  autodeploy:
    driver: local

secrets:
  jenkins_user:
    file: jenkins_user.txt
  jenkins_pass:
    file: jenkins_pass.txt
  github_user:
    file: github_user.txt
  github_pass:
    file: github_pass.txt
