---
version: '3.3'
services:
  db:
    image: novucs/derby:10.14.2.0-jdk11-slim
    volumes:
      - db-data:/dbs

  app:
    image: novucs/glassfish:5.1.0-jdk8-slim
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - deployments:/app/glassfish/domains/domain1/autodeploy

  jenkins:
    build: jenkins
    ports:
      - "8081:8080"
    secrets:
      - jenkins_user
      - jenkins_pass
    volumes:
      - deployments:/tmp/deployments

volumes:
  db-data:
  deployments:

secrets:
  jenkins_user:
    file: jenkins_user.txt
  jenkins_pass:
    file: jenkins_pass.txt
